// Pure permission constants and types shared by client and server code.

export const ENHANCED_PERMISSIONS = {
  GENERAL: {
    VIEW_FORUM: 'general:view_forum',
    SEARCH: 'general:search',
    VIEW_PROFILES: 'general:view_profiles',
    USE_TAGGING: 'general:use_tagging',
    BYPASS_FLOOD_CHECK: 'general:bypass_flood_check',
    IGNORE_USER_PRIVACY: 'general:ignore_user_privacy',
    BYPASS_MAXIMUM_MESSAGE_COUNT: 'general:bypass_maximum_message_count',
    RECEIVE_ADMIN_EMAIL: 'general:receive_admin_email',
  },
  PROFILE: {
    EDIT_OWN_PROFILE: 'profile:edit_own_profile',
    UPLOAD_AVATAR: 'profile:upload_avatar',
    EDIT_SIGNATURE: 'profile:edit_signature',
    USE_SIGNATURE: 'profile:use_signature',
    EDIT_CUSTOM_TITLE: 'profile:edit_custom_title',
    FOLLOW_USERS: 'profile:follow_users',
    IGNORE_USERS: 'profile:ignore_users',
    VIEW_ONLINE_STATUS: 'profile:view_online_status',
    EDIT_PRIVACY_SETTINGS: 'profile:edit_privacy_settings',
    CHANGE_USERNAME: 'profile:change_username',
    EDIT_DATE_OF_BIRTH: 'profile:edit_date_of_birth',
    VIEW_WARNING_DETAILS: 'profile:view_warning_details',
  },
  THREAD: {
    VIEW_THREADS: 'thread:view_threads',
    VIEW_CONTENT: 'thread:view_content',
    CREATE_THREAD: 'thread:create_thread',
    REPLY_TO_THREAD: 'thread:reply_to_thread',
    EDIT_OWN_POSTS: 'thread:edit_own_posts',
    DELETE_OWN_POSTS: 'thread:delete_own_posts',
    EDIT_ANY_POST: 'thread:edit_any_post',
    DELETE_ANY_POST: 'thread:delete_any_post',
    VIEW_DELETED_POSTS: 'thread:view_deleted_posts',
    UNDELETE_POSTS: 'thread:undelete_posts',
    MOVE_THREADS: 'thread:move_threads',
    COPY_THREADS: 'thread:copy_threads',
    MERGE_THREADS: 'thread:merge_threads',
    LOCK_THREADS: 'thread:lock_threads',
    STICK_THREADS: 'thread:stick_threads',
    RATE_POSTS: 'thread:rate_posts',
    VIEW_POST_RATINGS: 'thread:view_post_ratings',
    POST_WITHOUT_APPROVAL: 'thread:post_without_approval',
    APPROVE_UNAPPROVED_POSTS: 'thread:approve_unapproved_posts',
    BYPASS_DUPLICATE_CHECK: 'thread:bypass_duplicate_check',
    FEATURE_THREADS: 'thread:feature_threads',
  },
  MEDIA: {
    UPLOAD_ATTACHMENTS: 'media:upload_attachments',
    VIEW_ATTACHMENTS: 'media:view_attachments',
    DELETE_OWN_ATTACHMENTS: 'media:delete_own_attachments',
    DELETE_ANY_ATTACHMENTS: 'media:delete_any_attachments',
    USE_BBCODE: 'media:use_bbcode',
    USE_HTML: 'media:use_html',
    EMBED_MEDIA: 'media:embed_media',
    USE_CUSTOM_BBCODE: 'media:use_custom_bbcode',
  },
  CONVERSATION: {
    START_CONVERSATIONS: 'conversation:start_conversations',
    REPLY_TO_CONVERSATIONS: 'conversation:reply_to_conversations',
    EDIT_OWN_MESSAGES: 'conversation:edit_own_messages',
    DELETE_OWN_MESSAGES: 'conversation:delete_own_messages',
    LEAVE_CONVERSATIONS: 'conversation:leave_conversations',
    INVITE_TO_CONVERSATIONS: 'conversation:invite_to_conversations',
    UPLOAD_ATTACHMENTS: 'conversation:upload_attachments',
    BYPASS_PRIVACY: 'conversation:bypass_privacy',
    EDIT_ANY_MESSAGE: 'conversation:edit_any_message',
    DELETE_ANY_MESSAGE: 'conversation:delete_any_message',
  },
  MODERATION: {
    VIEW_MODERATION_LOG: 'moderation:view_moderation_log',
    DELETE_POSTS: 'moderation:delete_posts',
    UNDELETE_POSTS: 'moderation:undelete_posts',
    EDIT_POSTS: 'moderation:edit_posts',
    MOVE_POSTS: 'moderation:move_posts',
    WARN_USERS: 'moderation:warn_users',
    BAN_USERS: 'moderation:ban_users',
    MANAGE_REPORTED_CONTENT: 'moderation:manage_reported_content',
    VIEW_IP_ADDRESSES: 'moderation:view_ip_addresses',
    MANAGE_SPAM: 'moderation:manage_spam',
    CLEAN_SPAM: 'moderation:clean_spam',
    BYPASS_USER_PRIVACY: 'moderation:bypass_user_privacy',
  },
  ADMIN: {
    ACCESS_ADMIN_PANEL: 'admin:access_admin_panel',
    MANAGE_USERS: 'admin:manage_users',
    MANAGE_ROLES: 'admin:manage_roles',
    MANAGE_PERMISSIONS: 'admin:manage_permissions',
    MANAGE_NODES: 'admin:manage_nodes',
    MANAGE_TROPHIES: 'admin:manage_trophies',
    MANAGE_BB_CODES: 'admin:manage_bb_codes',
    VIEW_STATISTICS: 'admin:view_statistics',
    MANAGE_SETTINGS: 'admin:manage_settings',
    MANAGE_STYLE_PROPERTIES: 'admin:manage_style_properties',
    MANAGE_TEMPLATES: 'admin:manage_templates',
    MANAGE_PHRASES: 'admin:manage_phrases',
    RUN_MAINTENANCE: 'admin:run_maintenance',
    MANAGE_ADD_ONS: 'admin:manage_add_ons',
  },
  SPECIAL: {
    SUPER_ADMIN: 'special:super_admin',
    SYSTEM_USER: 'special:system_user',
    GUEST_ACCESS: 'special:guest_access',
  },
} as const

export type PermissionCategory = keyof typeof ENHANCED_PERMISSIONS
export type PermissionKey = string
export type PermissionValue<T extends PermissionCategory> =
  typeof ENHANCED_PERMISSIONS[T][keyof typeof ENHANCED_PERMISSIONS[T]]

export const ALL_ENHANCED_PERMISSIONS = Object.values(ENHANCED_PERMISSIONS).reduce(
  (acc, category) => ({ ...acc, ...category }),
  {}
) as Record<string, string>

export const PERMISSIONS = {
  ADMIN_ACCESS: 'admin.access',
  ADMIN_USERS_MANAGE: 'admin.users.manage',
  ADMIN_ROLES_MANAGE: 'admin.roles.manage',
  ADMIN_CATEGORIES_MANAGE: 'admin.categories.manage',
  ADMIN_SETTINGS_MANAGE: 'admin.settings.manage',
  ADMIN_ANALYTICS_VIEW: 'admin.analytics.view',
  POSTS_CREATE: 'posts.create',
  POSTS_EDIT_OWN: 'posts.edit.own',
  POSTS_EDIT_ALL: 'posts.edit.all',
  POSTS_DELETE_OWN: 'posts.delete.own',
  POSTS_DELETE_ALL: 'posts.delete.all',
  POSTS_PIN: 'posts.pin',
  POSTS_FEATURE: 'posts.feature',
  POSTS_LOCK: 'posts.lock',
  POSTS_TAG: 'posts.tag',
  COMMENTS_CREATE: 'comments.create',
  COMMENTS_EDIT_OWN: 'comments.edit.own',
  COMMENTS_EDIT_ALL: 'comments.edit.all',
  COMMENTS_DELETE_OWN: 'comments.delete.own',
  COMMENTS_DELETE_ALL: 'comments.delete.all',
  USERS_VIEW_PROFILES: 'users.view.profiles',
  USERS_EDIT_PROFILE: 'users.edit.profile',
  USERS_MANAGE_ROLES: 'users.manage.roles',
  USERS_BAN: 'users.ban',
  FILES_UPLOAD: 'files.upload',
  FILES_DELETE_OWN: 'files.delete.own',
  FILES_DELETE_ALL: 'files.delete.all',
  MODERATE_CONTENT: 'moderate.content',
  MODERATE_USERS: 'moderate.users',
  MODERATE_REPORTS: 'moderate.reports',
  USERS_REPORT: 'users.report',
  USERS_WATCH: 'users.watch',
} as const

export const ROLES = {
  SUPER_ADMIN: 'super_admin',
  ADMIN: 'admin',
  STAFF: 'staff',
  MOD: 'mod',
  AUTHOR: 'author',
  MEMBER: 'member',
} as const